[package]
name = "sqloxide"
version = "0.25.0"
authors = ["Will Eaton <me@wseaton.com>"]
edition = "2018"

[lib]
name = "sqloxide"
crate-type = ["cdylib"]

[dependencies]
pythonize = "0.18"

[dependencies.pyo3]
version = "0.19.0"
features = ["extension-module"]

[dependencies.sqlparser]
version = "0.34.0"
features = ["json_example"]
