# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: blacken
on:
  workflow_call
jobs:
  build:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Ruff & isort
        run: pip install --upgrade ruff isort pymmh3
      - name: Run Ruff
        run: ruff format opteryx
#      - name: Run isort
#        run: isort --check-only .
