name: Secrets Scanner
on: [push]

jobs:
  trufflehog:
    name: TruffleHog Secrets Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master

  fides:
    name: Fides Secrets Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: fides-scanner
        uses: joocer/fides@master